runtime plugins/configuratuion.vim
runtime plugins/plugins.vim
runtime plugins/plugins_configurations.vim
runtime plugins/color32schemes.vim
runtime plugins/statusline.vim
"source $HOME/.config/nvim/ale.vim
runtime plugins/coc.vim
runtime plugins/autostart.vim
runtime plugins/browser.vim
runtime plugins/cmake.vim
runtime plugins/cpp-modern.vim
runtime plugins/floaterm.vim
runtime plugins/utisnips.vim
runtime plugins/vista.vim
runtime plugins/fswtich.vim
runtime plugins/mappings.vim
